name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flet deep-translator

      - name: Build APK
        run: |
          # Sizning faylingiz nomi tarjimon3.py
          flet build apk tarjimon3.py

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mening-tarjimon-ilovam
          path: build/apk/*.apk
