name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Eng yangi v4 versiya

      - name: Set up Python
        uses: actions/setup-python@v5 # Eng yangi v5 versiya
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install flet deep-translator
          
      - name: Build APK
        run: |
          # Fayl nomingiz tarjimon3.py ekanligini hisobga oldim
          flet build apk tarjimon3.py

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Eng yangi v4 versiya
        with:
          name: mening-tarjimonim-v1
          path: build/apk/*.apk
