name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet
        run: |
          pip install flet deep-translator

      - name: Build Android APK
        run: |
          # Diqqat: Faylingiz nomi tarjimon3.py bo'lishi shart
          flet build apk tarjimon3.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mening-tarjimon-ilovam
          path: build/apk/*.apk
